docs_dir: mkdocs
site_dir: docs
site_name: zfs-helper
site_description: Privileged helper for tightly controlled ZFS operations
repo_url: https://github.com/<your-username>/zfs-helper
repo_name: zfs-helper
nav:
  - Home: index.md
  - Installation: installation.md
  - Policy: policy.md
  - Release: release.md
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - toc:
      permalink: true
