docs_dir: mkdocs
site_dir: docs
site_name: ZFS Helper
site_description: Secure ZFS delegation helper for unprivileged services
repo_url: https://github.com/akarasulu/zfs-helper
repo_name: zfs-helper
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - Policy Configuration: policy.md
  - Architecture & Design: design.md
  - Testing Framework: testing.md
  - Release Process: release.md
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
