#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/utsname.h>
#include <sys/sysinfo.h>
#include <time.h>

void print_header() {
    printf("\n");
    printf("╔══════════════════════════════════════════════════════════╗\n");
    printf("║                     SYSTEM INFORMATION                  ║\n");
    printf("║                  Generated by sys-info                  ║\n");
    printf("╚══════════════════════════════════════════════════════════╝\n");
    printf("\n");
}

void print_system_info() {
    struct utsname uname_data;
    struct sysinfo sys_info;
    
    if (uname(&uname_data) != 0) {
        perror("uname");
        return;
    }
    
    if (sysinfo(&sys_info) != 0) {
        perror("sysinfo");
        return;
    }
    
    printf("🖥️  System Information:\n");
    printf("   Operating System: %s\n", uname_data.sysname);
    printf("   Kernel Version:   %s\n", uname_data.release);
    printf("   Architecture:     %s\n", uname_data.machine);
    printf("   Hostname:         %s\n", uname_data.nodename);
    printf("\n");
    
    // Memory information
    printf("💾 Memory Information:\n");
    printf("   Total RAM:        %.2f GB\n", sys_info.totalram / (1024.0 * 1024.0 * 1024.0));
    printf("   Free RAM:         %.2f GB\n", sys_info.freeram / (1024.0 * 1024.0 * 1024.0));
    printf("   Used RAM:         %.2f GB\n", (sys_info.totalram - sys_info.freeram) / (1024.0 * 1024.0 * 1024.0));
    printf("   Total Swap:       %.2f GB\n", sys_info.totalswap / (1024.0 * 1024.0 * 1024.0));
    printf("\n");
    
    // System load and uptime
    printf("⚡ Performance:\n");
    printf("   Load Average:     %.2f, %.2f, %.2f\n", 
           sys_info.loads[0]/65536.0, sys_info.loads[1]/65536.0, sys_info.loads[2]/65536.0);
    
    long uptime_days = sys_info.uptime / 86400;
    long uptime_hours = (sys_info.uptime % 86400) / 3600;
    long uptime_minutes = (sys_info.uptime % 3600) / 60;
    
    printf("   Uptime:           %ld days, %ld hours, %ld minutes\n", 
           uptime_days, uptime_hours, uptime_minutes);
    printf("   Number of CPUs:   %d\n", get_nprocs());
    printf("\n");
}

void print_cpu_info() {
    FILE *cpuinfo = fopen("/proc/cpuinfo", "r");
    if (!cpuinfo) {
        printf("❌ Could not read CPU information\n");
        return;
    }
    
    char line[256];
    char cpu_model[256] = "Unknown";
    float cpu_freq = 0.0;
    
    printf("🔧 CPU Information:\n");
    
    while (fgets(line, sizeof(line), cpuinfo)) {
        if (strncmp(line, "model name", 10) == 0) {
            char *value = strchr(line, ':');
            if (value) {
                value += 2; // Skip ": "
                strncpy(cpu_model, value, sizeof(cpu_model) - 1);
                cpu_model[strlen(cpu_model) - 1] = '\0'; // Remove newline
                break;
            }
        }
    }
    
    fclose(cpuinfo);
    
    printf("   Model:            %s\n", cpu_model);
    printf("   Cores:            %d\n", get_nprocs());
    printf("\n");
}

void print_disk_info() {
    printf("💽 Disk Usage:\n");
    
    // Read disk usage from df command
    FILE *df = popen("df -h / 2>/dev/null", "r");
    if (df) {
        char line[256];
        int line_count = 0;
        
        while (fgets(line, sizeof(line), df)) {
            line_count++;
            if (line_count == 2) { // Second line contains the data
                char filesystem[64], size[16], used[16], avail[16], use_percent[16], mounted[64];
                if (sscanf(line, "%s %s %s %s %s %s", filesystem, size, used, avail, use_percent, mounted) == 6) {
                    printf("   Root Filesystem:  %s\n", filesystem);
                    printf("   Total Size:       %s\n", size);
                    printf("   Used:             %s (%s)\n", used, use_percent);
                    printf("   Available:        %s\n", avail);
                }
                break;
            }
        }
        pclose(df);
    }
    printf("\n");
}

void print_network_info() {
    printf("🌐 Network Information:\n");
    
    // Try to get network interfaces
    FILE *interfaces = popen("ip -4 addr show 2>/dev/null | grep inet | grep -v 127.0.0.1", "r");
    if (interfaces) {
        char line[256];
        int count = 0;
        
        while (fgets(line, sizeof(line), interfaces) && count < 5) {
            // Extract IP addresses
            char *inet_pos = strstr(line, "inet ");
            if (inet_pos) {
                inet_pos += 5; // Skip "inet "
                char *space_pos = strchr(inet_pos, '/');
                if (space_pos) {
                    *space_pos = '\0';
                    printf("   IP Address:       %s\n", inet_pos);
                    count++;
                }
            }
        }
        pclose(interfaces);
        
        if (count == 0) {
            printf("   No network interfaces found\n");
        }
    }
    printf("\n");
}

void print_usage() {
    printf("Usage: sys-info [OPTIONS]\n");
    printf("\n");
    printf("Advanced system information utility\n");
    printf("\n");
    printf("Options:\n");
    printf("  -h, --help     Show this help message\n");
    printf("  -v, --version  Show version information\n");
    printf("  -q, --quiet    Minimal output\n");
    printf("\n");
    printf("Examples:\n");
    printf("  sys-info       Show full system information\n");
    printf("  sys-info -q    Show brief system summary\n");
}

void print_version() {
    printf("sys-info version 3.2.1\n");
    printf("Built for GH-Repos demonstration\n");
    printf("Compiled on %s at %s\n", __DATE__, __TIME__);
}

int main(int argc, char *argv[]) {
    int quiet = 0;
    
    // Parse command line arguments
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            print_usage();
            return 0;
        } else if (strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--version") == 0) {
            print_version();
            return 0;
        } else if (strcmp(argv[i], "-q") == 0 || strcmp(argv[i], "--quiet") == 0) {
            quiet = 1;
        } else {
            printf("Unknown option: %s\n", argv[i]);
            print_usage();
            return 1;
        }
    }
    
    if (quiet) {
        struct utsname uname_data;
        struct sysinfo sys_info;
        
        if (uname(&uname_data) == 0 && sysinfo(&sys_info) == 0) {
            printf("System: %s %s (%s)\n", uname_data.sysname, uname_data.release, uname_data.machine);
            printf("Memory: %.1f/%.1f GB used\n", 
                   (sys_info.totalram - sys_info.freeram) / (1024.0 * 1024.0 * 1024.0),
                   sys_info.totalram / (1024.0 * 1024.0 * 1024.0));
            printf("Load: %.2f\n", sys_info.loads[0]/65536.0);
        }
    } else {
        print_header();
        print_system_info();
        print_cpu_info();
        print_disk_info();
        print_network_info();
        
        printf("📦 Package Information:\n");
        printf("   Package:          sys-info\n");
        printf("   Version:          3.2.1\n");
        printf("   Maintainer:       GH-Repos Demo\n");
        printf("   Repository:       GitHub Pages APT Repository\n");
        printf("\n");
        
        time_t now = time(NULL);
        printf("Generated on: %s", ctime(&now));
    }
    
    return 0;
}